### ISSUE TITLE
Reduce just-in-time Dockerfile manipulation for Jenkins

### ISSUE THREAD

**Issue by vkhazin** [redyork/lenj#1]
Streamlining the Docker build process to reduce the number of steps and to speedup the build

1. Instead of cloning the official jenkins docker repo and then modifying the Dockerfile to add components into it.
2. Create a subfolder in this repo for jenkins ci with all jenkins artifacts
3. Create a new Dockerfile inside this folder to inherit from jenkins/jenkins:lts
4. Add components required components to the new Dockerfile rather than manipulating the original Dockerfile with artifacts from the jenkins subfolder
5. Bake dhparam into the new Dockerfile rather than generating a new one during image build process, the maintainer can run openssl to refresh dhparam separately from image build proccess
6. Run certs generation as a part of the Jenkins image build process to bake the certs into the image without a reliance on a shared file system between LetsEncrypt and Jenkins container during run-time

**Comment by redyork** [comment]
Done in v3.2 commit
