### ISSUE TITLE
LetsEncrypt integration

### ISSUE THREAD

**Issue by vkhazin** [redyork/lenj#2]
To my (limited) knowledge there are two modes integrating with [LetsEncrypt](https://letsencrypt.org/getting-started/):

1. run letsencrypt as a command line to generate certs
2. letsencrypt support is built-in by the hosting provider

What I am looking for is a self-contained Jenkins+NginX container that can either generate cert by running letsencrypt internally to the container itself.
Or
Jenkins+NginX self-contained container that integrates with LetsEncrypt running in a separate container to generate/re-generate the certs.

I am not sure whether the latter is possible with docker infrastructure without a reliance on a shared folder between two containers.

The reason I cannot rely on a shared folder is that the shared-folder approach may or may not work as expected across different container providers, e.g. aws, openshift and etc.

**Comment by redyork** [comment]
Done in v3.2 commit
